const users = [
    {
        id: 'FQw5fHnzhPMW2413t0ORL',
        name: 'Alessandra Silva',
        email: 'a.silva@frontend.infojr.br',
        password: 'alessandra_frontend',
        projectProgress: 65,
        codeQuality: 84,
    },
    {
        id: 'zTyRv6-HpQHyyjStGgalP',
        name: 'Alexandre Shyjada',
        email: 'a.shyjada@frontend.infojr.br',
        password: 'alexandre_frontend',
        projectProgress: 95,
        codeQuality: 78,
    },
    {
        id: 'QpvKItPjmF81vZioxeWFv',
        name: 'Beatriz Morais',
        email: 'b.morais@frontend.infojr.br',
        password: 'beatriz_frontend',
        projectProgress: 36,
        codeQuality: 32,
    },
    {
        id: 'LzsefwFh1erdGMJBgNAHL',
        name: 'Bruno Lucas',
        email: 'b.lucas@frontend.infojr.br',
        password: 'bruno_frontend',
        projectProgress: 19,
        codeQuality: 77,
    },
    {
        id: '99Y5Ivi8JJAnhNvw1pkaw',
        name: 'Caio Oliveira',
        email: 'c.oliveira@frontend.infojr.br',
        password: 'caio_frontend',
        projectProgress: 81,
        codeQuality: 67,
    },
    {
        id: 'D1F4zRQRhGpqPdWxLUSe0',
        name: 'João Victor',
        email: 'j.victor@frontend.infojr.br',
        password: 'joao_frontend',
        projectProgress: 69,
        codeQuality: 73,
    },
    {
        id: 'dqAtaq-8PNKJwlFpK8nz7',
        name: 'Liang Sek King',
        email: 'l.king@frontend.infojr.br',
        password: 'liang_frontend',
        projectProgress: 98,
        codeQuality: 62,
    },
    {
        id: 'jFV8lWdTw2-ZuncpIXLKU',
        name: 'Lucas Morais',
        email: 'l.morais@frontend.infojr.br',
        password: 'lucas_frontend',
        projectProgress: 50,
        codeQuality: 83,
    },
    {
        id: 'nYFjFhsgBjx0ndM1FaUOS',
        name: 'Lávio Dias',
        email: 'l.dias@frontend.infojr.br',
        password: 'lavio_frontend',
        projectProgress: 76,
        codeQuality: 95,
    },
    {
        id: 'IsJT67IISWOkb3YVbnS_R',
        name: 'Matheus Quevedo',
        email: 'm.quevedo@frontend.infojr.br',
        password: 'matheus_frontend',
        projectProgress: 57,
        codeQuality: 86,
    },
    {
        id: '8WkSl5J33lRq3mAFin0Fk',
        name: 'Michael Kelvin',
        email: 'm.kelvin@frontend.infojr.br',
        password: 'michael_frontend',
        projectProgress: 25,
        codeQuality: 23,
    },
];

export default users;
